apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: kofimorrison/multi-client
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "2000m"
          limits:
            memory: "128Mi"
            cpu: "2000m"
        ports:
          - containerPort: 3000