name: Deploy Multi Image App
on:
  push:
    branches:
      - "master"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t kofimorrison/react-test -f ./client/Dockerfile.dev ./client
        
      # - run: docker run -e CI=true kofimorrison/react-test npm test
      # - run: docker build -t kofimorrison/multi-client ./client 
      # - run: docker build -t kofimorrison/multi-nginx ./nginx 
      # - run: docker build -t kofimorrison/multi-server ./server
      # - run: docker build -t kofimorrison/multi-worker ./worker
      # - run: docker push kofimorrison/multi-client
      # - run: docker push kofimorrison/multi-nginx
      # - run: docker push kofimorrison/multi-server
      # - run: docker push kofimorrison/multi-worker
        
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-image-docker
      #     environment_name: Multiimagedocker-env
      #     existing_bucket_name: elasticbeanstalk-eu-central-1-584336754720
      #     region: eu-central-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip